### ISSUE TITLE
allow configuration of location of lammps executable 

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps#10]
Currently the lammps-wrapper assumes that there is an executable called "lammps" that can be found in the PATH and an exception is thrown if this is not the case.

**Comment by mehdisadeghi** [comment]
The name of the executable is configurable via `SIM_LAMMPS_BIN` env variable. This is enough for now since we plan to support mostly (or only) lammps shared object (which is installed along with its python wrapper in python site-packages). Closing.
