### ISSUE TITLE
Finish DEM prototype

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps#104]
The DEM pro-type needs the following steps to be completed
* testing of DEM wrapper
* documentation
*  complete configuration (YOUNGS_MODULUS, POISSONS_RATIO, and material relations for coefficientrestitute and coefficientFriction)
*  support walls
*  DEM wrapper using INTERNAL interface

**Comment by mehdisadeghi** [comment]
We have moved DEM engine to *simphony_liggghts* repository. I'll close this issue.
