### ISSUE TITLE
ipython crashes when launced from dir simlammps

### ISSUE THREAD

**Issue by jeremy-rutman** [simphony/simphony-lammps#113]
problem exactly as here:
https://github.com/ipython/ipython/issues/6486

naming a directory io apparently will cause trouble

**Comment by mehdisadeghi** [comment]
It works for me. However I can not import `simlammps` package inside ipython. Do you still encounter this problem? What is your '$PYTHONPATH' BTW?

**Comment by mehdisadeghi** [comment]
@jeremy-rutman I can't reproduce this issue (probably it is fixed by latest updates to ipython). Closing. Feel free to reopen if you experience any problems.
