### ISSUE TITLE
evaluate how to use non-approved (i.e. provisional) CUBA keywords

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps#28]
In simphony-lammps, we are using keywords that aren't in CUBA yet.

To circumvent this, I was altering simphony-common (updating cuba.yml and then the associated code). This could be problematic when simphony-lammps-md is being used with other engines/visualization plugins.

in issue #26 which was implemented in PR #27, we stopped altering simhony-common and instead use a CUBAExtension enum for our provisional CUBA keywords and used a normal dictionary instead of DataContainer in the cases when these keywords would be used. 

Is there another way to work with non-approved CUBA keywods this?

**Comment by mehdisadeghi** [comment]
New `CUBA` keys should go to simphony-common. Extra CUBAs are not supported anymore.
