### ISSUE TITLE
improve  examples/simple_nve/

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps#40]
make the example/validation more user friendly by 
- options so that user can run the example:
  - run the simphony by itself
  - run simphony (`simple_nve.py`) and lammps (`lammps_input.script`) and see the validation results 
- explore if we can remove `data_input_from_sim.lammps` from `lammps_input.script` by using some other lammps-commands (`create_atoms` etc.)

**Comment by mehdisadeghi** [comment]
The example works with the new design. Closing.
