### ISSUE TITLE
create package for LAMMPS on launchpad

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps#60]
To speed up testing and improve ease-of-use, we should create two packages for:
- lammps executable   (to be used by the FILE-IO wrapper)
- python interface to LAMMPS   (to be used by the INTERNAL wrapper)

**Comment by nathanfranklin** [comment]
There exists the following:  https://launchpad.net/lammps

"The "trunk" series represents the primary line of development rather than a stable release branch."

**Comment by mehdisadeghi** [comment]
There is a ppa for LAMMPS which is described on their download page and contains the lammps executable but not the shared object. Moreover, it's product owners responsibility.

**Comment by dpinte** [comment]
also note that @stefanoborini provided working solution builtd on top of `edm` and Enthougth eggs https://github.com/simphony/buildrecipe-lammps_liggghts_python. I'm not sure who's the product owner in this case.
