### ISSUE TITLE
poor error message when lammps executable cannot be found

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps#74]
lammps-md (FILE-IO) expects that `lammps` executable is in the user's path.  Otherwise an error occurs.  

The current error message doesn't help the user in fixing the problem.  See the following error message

```
pc-p561(~/local) python simphony_dev/simphony-lammps-md/examples/simple_nve/simple_nve.py 
Traceback (most recent call last):
  File "simphony_dev/simphony-lammps-md/examples/simple_nve/simple_nve.py", line 226, in <module>


wrapper.run()
  File "/W5/fra/local/simphony_dev/simphony-lammps-md/simlammps/lammps_wrapper.py", line 191, in run
    lammps_process = LammpsProcess(log_directory=temp_dir)
  File "/W5/fra/local/simphony_dev/simphony-lammps-md/simlammps/io/lammps_process.py", line 45, in __init__
    raise RuntimeError(msg)
RuntimeError: LAMMPS could not be started. stdout/err:
```

**Comment by nathanfranklin** [comment]
@TobiasRasp

**Comment by mehdisadeghi** [comment]
Since in the new design `Simulation` class from `simphony-common` is responsible to run the wrappers, it is its responsibility to catch errors and display them properly. Closing.

**Comment by dpinte** [comment]
@mehdisadeghi looking at the `Simulation` code (https://github.com/simphony/simphony-common/blob/master/simphony/cuds/simulation.py#L35), this seems ambitious. That class is not aware of any implementation details of the wrappers and will more than likely end up with an awful catch-all block. The wrappers have all the knowledge about the internals of what they run and should be in charge of a proper error reporting to support the simulation class.
