### ISSUE TITLE
skip unittests when either FILE-IO or INTERNAL are not available

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps#75]
Currently all unit tests are run for both the FILE-IO wrapper and INTENRAL wrapper.  

If the user only has the requirements for the FILE-IO wrapper installled (i.e. has a "lammps" executable) and not the lammps python library needed for the INTERNAL wrapper, then the INTERNAL wrapper tests could be skipped.

**Comment by mehdisadeghi** [comment]
We run tests on travis which has both preinstalled (in the yaml file). So closing for now unless need arises (which is unlikely).
