### ISSUE TITLE
Extend bc options (CUBAExtension.BOX_FACES) to support other periodic/non-periodic types

### ISSUE THREAD

**Issue by TobiasRasp** [simphony/simphony-lammps#80]
Up to now, only periodic boundary conditions are provided by the lammps-md-wrapper. The others may easily be added by extending the mapping in script_writer.py/get_boundary, e.g.
mappings = {'periodic': 'p', 'fixed': 'f', 'shrink': 's'}

**Comment by ahashibon** [comment]
of course 'periodic' and 'fixed', etc should be given by CUBA in SimPhoNy side.

**Comment by nathanfranklin** [comment]
from http://lammps.sandia.gov/doc/boundary.html:
```
  boundary args = x y z
    x,y,z = p or s or f or m, one or two letters
    p is periodic
    f is non-periodic and fixed
    s is non-periodic and shrink-wrapped
    m is non-periodic and shrink-wrapped with a minimum value`
```
do we want to support exactly the 4 types?  or a subset (e.g. just fixed and periodic)?

**Comment by nathanfranklin** [comment]
Also from http://lammps.sandia.gov/doc/boundary.html: ```Two letters assigns the first style to the lower face and the second style to the upper face.```

Is having different styles for the lower and upper face common?  should that be supported?

**Comment by nathanfranklin** [comment]
> of course 'periodic' and 'fixed', etc should be given by CUBA in SimPhoNy side. 



we currently using BOX_FACES as a keyword to store a for list of strings:
```
wrapper.BC_extension[lammps.CUBAExtension.BOX_FACES] = ["periodic",
                                                        "periodic",
                                                        "periodic"]
```



any particular names you have in mind?  CUBA::PERIODIC/CUBA::FIXED or CUBA::BOX_FACE_PERIODIC/CUBA::BOX_FACE_FIXED? An example would look like the following:
```
wrapper.BC_extension[lammps.CUBAExtension.BOX_FACES] = [CUBA::BOX_FACE_PERIODIC,
                                                        CUBA::BOX_FACE_PERIODIC,
                                                        CUBA::BOX_FACE_PERIODIC]
```

Here, we are having CUBA used as a keyword (`BOX_FACES`) and as a value (`PERIODIC`).  If PERIODIC is only used as a value, it might be worth considering making a separate enum which contained only the valid values for `BOX_FACES`:   `CUBA_BOX_FACES::PERIODIC`, `CUBA_BOX_FACES::FIXED`.....

**Comment by TobiasRasp** [comment]
In my opinion, opposing faces of a box should have the same condition. 
Any name suggestion is fine for me.

**Comment by mehdisadeghi** [comment]
`CUBAExtension` is removed and merged into `CUBA`. Any addition should be filed against simphony-common. Closing.
