### ISSUE TITLE
Investigate segementation fault when NUMBER_OF_TIME_STEPS is high in tests

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-lammps#90]
See  b3893add842f8e8f8ae4cd740959b9c51a2e13f6 for information

Basically, when using the INTERNAL wrapper a LAMMPS segmenation fault occurs when the NUMBER_OF_TIME_STEPS is set to something high (like 500 or 10000 steps) in the unit tests.

The FILE-IO wrapper runs fine.

**Comment by mehdisadeghi** [comment]
I've upgraded lammps to new stable version from 11 August 2017 and it apparently works fine now.
